### ISSUE TITLE
HxCCore is conflicting with it's own config

### ISSUE THREAD

**Issue by ammy55** [HxCKDMS/HxCCore#26]
In an instance with just HxCCore and forge i can not launch the game twice in a row. The first launch it starts without having a config, generates it, and launches fine. The second launch however it crashes with the following crash report. http://pastebin.com/rPd8whe7
A temporary workaround is to delete HxCCore.cfg. This crash does also occur when HxCEnchants is installed but in that case you have to delete both config files.

**Comment by karelmikie3** [comment]
please update your java, it is outdated.

**Comment by DrZed** [comment]
It's not a conflict, our mod requires Java 8 of which it says so on the download page, also it doesn't crash on creation because it only crashes when reading existing config since we use a new method in java 8.
